# Generated by Django 3.2.3 on 2021-05-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releasedate', models.DateTimeField(verbose_name='date published')),
                ('version', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_lib.games')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_lib.platforms')),
            ],
        ),
        migrations.AddField(
            model_name='platforms',
            name='_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_lib.releases'),
        ),
        migrations.AddField(
            model_name='games',
            name='_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_lib.releases'),
        ),
    ]
