# Generated by Django 3.2.3 on 2021-05-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('releasedate', models.DateTimeField(verbose_name='date published')),
                ('version', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_lib.games')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_lib.platforms')),
            ],
        ),
    ]
